services:
  auth-service:
    build:
      context: ./backend/auth-service
    container_name: auth-service
    restart: unless-stopped
    ports:
      - "5024:5024"
    environment:
      PORT: 5024
      NODE_ENV: production
      CLIENT_URL: http://localhost:8080
      COOKIE_SECURE: "false"
      MONGODB_URI: ${AUTH_MONGODB_URI:-mongodb+srv://username:password@cluster.mongodb.net/auth_db?retryWrites=true&w=majority}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET:-sasuke}
      JWT_ACCESS_EXPIRES: ${JWT_ACCESS_EXPIRES:-15m}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-supersecretrefreshkey}
      JWT_REFRESH_EXPIRES: ${JWT_REFRESH_EXPIRES:-7d}
      INTERNAL_SERVICE_SECRET: ${INTERNAL_SERVICE_SECRET:-super_internal_secret}
      OTP_RESEND_COOLDOWN_SECONDS: ${OTP_RESEND_COOLDOWN_SECONDS:-60}
      OTP_RATE_LIMIT_WINDOW_MINUTES: ${OTP_RATE_LIMIT_WINDOW_MINUTES:-15}
      OTP_RATE_LIMIT_MAX: ${OTP_RATE_LIMIT_MAX:-5}
      OTP_MAX_VERIFY_ATTEMPTS: ${OTP_MAX_VERIFY_ATTEMPTS:-5}
      OTP_ATTEMPT_BLOCK_MINUTES: ${OTP_ATTEMPT_BLOCK_MINUTES:-15}
      EMAIL_HOST: ${EMAIL_HOST:-smtp.gmail.com}
      EMAIL_PORT: ${EMAIL_PORT:-587}
      EMAIL_USER: ${EMAIL_USER:-change-me@example.com}
      EMAIL_PASS: ${EMAIL_PASS:-change-me}
      EMAIL_FROM: ${EMAIL_FROM:-change-me@example.com}

  admin-service:
    build:
      context: ./backend/admin-service
    container_name: admin-service
    restart: unless-stopped
    depends_on:
      - auth-service
    ports:
      - "5025:5025"
    environment:
      PORT: 5025
      NODE_ENV: production
      CLIENT_URL: http://localhost:8080
      MONGODB_URI: ${ADMIN_MONGODB_URI:-mongodb+srv://username:password@cluster.mongodb.net/admin_db?retryWrites=true&w=majority}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET:-sasuke}
      AUTH_SERVICE_URL: http://auth-service:5024
      INTERNAL_SERVICE_SECRET: ${INTERNAL_SERVICE_SECRET:-super_internal_secret}

  api-gateway:
    build:
      context: ./backend/api-gateway
    container_name: api-gateway
    restart: unless-stopped
    depends_on:
      - auth-service
      - admin-service
    ports:
      - "5026:5026"
    environment:
      PORT: 5026
      NODE_ENV: production
      CLIENT_URL: http://localhost:8080
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET:-sasuke}
      AUTH_SERVICE_URL: http://auth-service:5024
      ADMIN_SERVICE_URL: http://admin-service:5025

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: /api
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - api-gateway
    ports:
      - "8080:80"
