apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: admin-mongo-pvc
  namespace: smart-health
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-mongo
  namespace: smart-health
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-mongo
  template:
    metadata:
      labels:
        app: admin-mongo
    spec:
      containers:
        - name: mongo
          image: mongo:7
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: admin-mongo-storage
              mountPath: /data/db
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: admin-mongo-storage
          persistentVolumeClaim:
            claimName: admin-mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: admin-mongo
  namespace: smart-health
spec:
  selector:
    app: admin-mongo
  ports:
    - port: 27017
      targetPort: 27017
