apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - auth-service.yaml
  - admin-service.yaml
  - patient-service-deployment.yaml
  - patient-service-service.yaml
  - ai-chatbot-service-deployment.yaml
  - ai-chatbot-service-service.yaml
  - api-gateway.yaml
  - frontend.yaml
  - ingress.yaml
