apiVersion: v1
kind: Secret
metadata:
  name: smart-health-secrets
  namespace: smart-health
type: Opaque
stringData:
  AUTH_MONGODB_URI: replace-with-auth-mongodb-uri
  ADMIN_MONGODB_URI: replace-with-admin-mongodb-uri
  PATIENT_MONGODB_URI: replace-with-patient-mongodb-uri
  APPOINTMENT_MONGODB_URI: replace-with-appointment-mongodb-uri
  PAYMENT_MONGODB_URI: replace-with-payment-mongodb-uri
  DOCTOR_MONGODB_URI: replace-with-doctor-mongodb-uri
  NOTIFICATION_MONGODB_URI: replace-with-notification-mongodb-uri
  TELEMEDICINE_MONGODB_URI: replace-with-telemedicine-mongodb-uri
  JWT_ACCESS_SECRET: replace-with-access-secret
  JWT_REFRESH_SECRET: replace-with-refresh-secret
  INTERNAL_SERVICE_SECRET: replace-with-internal-service-secret
  EMAIL_USER: replace-with-email-user
  EMAIL_PASS: replace-with-email-password
  EMAIL_FROM: replace-with-email-from
  CLOUDINARY_CLOUD_NAME: replace-with-cloudinary-cloud-name
  CLOUDINARY_API_KEY: replace-with-cloudinary-api-key
  CLOUDINARY_API_SECRET: replace-with-cloudinary-api-secret
  GEMINI_API_KEY: replace-with-gemini-api-key
  GOOGLE_CLIENT_ID: change-me
  GOOGLE_CLIENT_SECRET: change-me
  GOOGLE_ENCRYPTION_KEY: change-me
  NOTIFY_LK_USER_ID: replace-with-notify-lk-user-id
  NOTIFY_LK_API_KEY: replace-with-notify-lk-api-key
  TWILIO_ACCOUNT_SID: change-me
  TWILIO_AUTH_TOKEN: change-me
  TWILIO_SMS_FROM: "+10000000000"
  TWILIO_WHATSAPP_FROM: whatsapp:+14155238886
