export const USER_ROLES = {
  PATIENT: "PATIENT",
  DOCTOR: "DOCTOR",
  ADMIN: "ADMIN",
  STAFF: "STAFF"
};

export const APPOINTMENT_STATUS = {
  HOLD: "HOLD",
  BOOKED: "BOOKED",
  CONFIRMED: "CONFIRMED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  NO_SHOW: "NO_SHOW",
  RESCHEDULED: "RESCHEDULED"
};

export const CONSULTATION_MODE = {
  IN_PERSON: "IN_PERSON",
  TELEMEDICINE: "TELEMEDICINE"
};

export const ALERT_SEVERITY = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  CRITICAL: "CRITICAL"
};
